### ISSUE TITLE
Question/Вопрос

### ISSUE THREAD

**Issue by vladi7** [levshun/SIMPAT-Verification#1]
Hello!

I was wondering about your research in ABAC verification. 

I found this paper of yours (I believe): "A Model Checking Based Approach for Verification of Attribute-Based Access Control Policies in Cloud Infrastructures", but I am not able to locate a free version of it. Is there any copy available for free (English or Russian). I would really appreciate any help.

Здравствуйте,

Меня очень заинтересовал ваша работа с титлом:"A Model Checking Based Approach for Verification of Attribute-Based Access Control Policies in Cloud Infrastructures"

Есть ли возможность получить эту работу бесплатно на русском(желательно) или английском языке, я бы очень хотел ее прочитать. 

Спасибо,
Влад

**Comment by vladi7** [comment]
Emailed instead, thanks

**Comment by levshun** [comment]
> Emailed instead, thanks

Hello, here is a link to paper in Russian: https://sccs.intelgr.com/archive/2019-04/17-Kotenko.pdf.
Hope it would help!

**Comment by vladi7** [comment]
Thank you very much!
